### ISSUE TITLE
项目里有灰色模式，获取CALayer的颜色(themeCGColor转换之后的颜色)进行灰度转换时，报错

### ISSUE THREAD

**Issue by carlchou00** [internetWei/llDark#7]
1、发生崩溃的情况：
项目里在进行灰色模式切换时，会获取calayer当前的颜色进行灰度转换，发现由themeCGColor转换过后的颜色不是有效的CGColor。(见下方截图，是项目里在进行灰色模式处理时的方法交换之后的处理逻辑)

2、更改LLDark库里UIColor+Dark.m中第50行的代码之后，可以顺利运行。
- (CGColorRef _Nonnull (^)(UIColor * _Nullable))themeCGColor {
    return ^(UIColor * _Nullable darkColor) {
        return (__bridge CGColorRef)self.themeColor(darkColor);
    };
}
改为：
- (CGColorRef _Nonnull (^)(UIColor * _Nullable))themeCGColor {
    return ^(UIColor * _Nullable darkColor) {
        return self.themeColor(darkColor).CGColor;
    };
}
<img width="1610" alt="Screen Shot 2021-01-19 at 4 25 21 PM" src="https://user-images.githubusercontent.com/13175918/105007854-78d69600-5a73-11eb-84e3-1fd9abb42d44.png">

**Comment by internetWei** [comment]
您好。
您不能这么修改，如果您将`(__bridge CGColorRef)self.themeColor(darkColor)`改为`self.themeColor(darkColor).CGColor`的话。
这会导致所有对CALayer设置的颜色在切换主题模式时都无法正常切换颜色。

因为CGColor不是一个OC对象，我无法对它增加分类扩展属性来保存深色颜色。所以这里返回的实际类型是UIColor而不是CGColor。但是我会在相关赋值方法中增加判断处理UIColor和CGColor。

麻烦您详细描述一下问题的经过，我也好为您提供帮助。

**Comment by carlchou00** [comment]
经过您的提醒，我明白了，实际上返回的颜色并不是CGColor而是UIColor，我在自己的项目里和您一样进行了颜色类型的判断之后解决该问题了，谢谢大佬，非常感谢！

**Comment by internetWei** [comment]
您好，请问您是如何获取到Layer的UIColor呢？麻烦您告知获取细节，我也好进一步优化。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: carlchou00 <notifications@github.com&gt;
发送时间: 2021年1月19日 17:47
收件人: internetWei/llDark <llDark@noreply.github.com&gt;
抄送: 布多 <internetWei@foxmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[internetWei/llDark] 项目里有灰色模式，获取CALayer的颜色(themeCGColor转换之后的颜色)进行灰度转换时，报错 (#7)





 
经过您的提醒，我明白了，实际上返回的颜色并不是CGColor而是UIColor，我在自己的项目里和您一样进行了颜色类型的判断之后解决该问题了，谢谢大佬，非常感谢！

**Comment by carlchou00** [comment]
> 您好，请问您是如何获取到Layer的UIColor呢？麻烦您告知获取细节，我也好进一步优化。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: carlchou00 <notifications@github.com&gt; 发送时间: 2021年1月19日 17:47 收件人: internetWei/llDark <llDark@noreply.github.com&gt; 抄送: 布多 <internetWei@foxmail.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[internetWei/llDark] 项目里有灰色模式，获取CALayer的颜色(themeCGColor转换之后的颜色)进行灰度转换时，报错 (#7) 经过您的提醒，我明白了，实际上返回的颜色并不是CGColor而是UIColor，我在自己的项目里和您一样进行了颜色类型的判断之后解决该问题了，谢谢大佬，非常感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，也是能过方法交换拿到setbackgroundcolor的参数之后，把CGColor转换成UIColor的


+ (void)swizzle {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [NFMethodSwizzleUtils swizzleInstanceMethodWithClass:[self class] OriginMethod:@selector(setBorderColor:) swappedMethod:@selector(nf_setBorderColor:)];
        [NFMethodSwizzleUtils swizzleInstanceMethodWithClass:[self class] OriginMethod:@selector(setShadowColor:) swappedMethod:@selector(nf_setShadowColor:)];
        [NFMethodSwizzleUtils swizzleInstanceMethodWithClass:[self class] OriginMethod:@selector(setBackgroundColor:) swappedMethod:@selector(nf_setBackgroundColor:)];
    });
}

- (void)nf_setBackgroundColor:(id)colorRef {
    if (self.themeTag != NFThemeNoDrawTag) {
        if ([colorRef isKindOfClass:UIColor.class]) {
            UIColor *color = (UIColor*)colorRef;
            [self nf_setBackgroundColor:(id)color.grayDraw.CGColor];
        } else {
            CGColorRef color = (__bridge CGColorRef)colorRef;
            [self nf_setBackgroundColor:(id)[UIColor colorWithCGColor:color].grayDraw.CGColor];
        }
    } else {
        [self nf_setBackgroundColor:colorRef];
    }
}

- (void)nf_setShadowColor:(id)colorRef {
    if (self.themeTag != NFThemeNoDrawTag) {
        if ([colorRef isKindOfClass:UIColor.class]) {
            UIColor *color = (UIColor*)colorRef;
            [self nf_setShadowColor:(id)color.grayDraw.CGColor];
        } else {
            CGColorRef color = (__bridge CGColorRef)colorRef;
            [self nf_setShadowColor:(id)[UIColor colorWithCGColor:color].grayDraw.CGColor];
        }
    } else {
        [self nf_setShadowColor:colorRef];
    }
}

- (void)nf_setBorderColor:(id)colorRef {
    if (self.themeTag != NFThemeNoDrawTag) {
        if ([colorRef isKindOfClass:UIColor.class]) {
            UIColor *color = (UIColor*)colorRef;
            [self nf_setBorderColor:(id)color.grayDraw.CGColor];
        } else {
            CGColorRef color = (__bridge CGColorRef)colorRef;
            [self nf_setBorderColor:(id)[UIColor colorWithCGColor:color].grayDraw.CGColor];
        }
    } else {
        [self nf_setBorderColor:colorRef];
    }
}

**Comment by internetWei** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    /:ok
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                internetwei
                            
                    
                        
                            
                                    internetwei@foxmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年01月20日 09:51，carlchou00<notifications@github.com> 写道： 






您好，请问您是如何获取到Layer的UIColor呢？麻烦您告知获取细节，我也好进一步优化。 发自我的iPhone

…

------------------ 原始邮件 ------------------ 发件人: carlchou00 <notifications@github.com> 发送时间: 2021年1月19日 17:47 收件人: internetWei/llDark <llDark@noreply.github.com> 抄送: 布多 <internetWei@foxmail.com>, Comment <comment@noreply.github.com> 主题: 回复：[internetWei/llDark] 项目里有灰色模式，获取CALayer的颜色(themeCGColor转换之后的颜色)进行灰度转换时，报错 (#7) 经过您的提醒，我明白了，实际上返回的颜色并不是CGColor而是UIColor，我在自己的项目里和您一样进行了颜色类型的判断之后解决该问题了，谢谢大佬，非常感谢！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



您好，也是能过方法交换拿到setbackgroundcolor的参数之后，把CGColor转换成UIColor的



(void)swizzle {

static dispatch_once_t onceToken;

dispatch_once(&onceToken, ^{

[NFMethodSwizzleUtils swizzleInstanceMethodWithClass:[self class] OriginMethod:@selector(setBorderColor:) swappedMethod:@selector(nf_setBorderColor:)];

[NFMethodSwizzleUtils swizzleInstanceMethodWithClass:[self class] OriginMethod:@selector(setShadowColor:) swappedMethod:@selector(nf_setShadowColor:)];

[NFMethodSwizzleUtils swizzleInstanceMethodWithClass:[self class] OriginMethod:@selector(setBackgroundColor:) swappedMethod:@selector(nf_setBackgroundColor:)];

});

}







(void)nf_setBackgroundColor:(id)colorRef {

if (self.themeTag != NFThemeNoDrawTag) {

if ([colorRef isKindOfClass:UIColor.class]) {

UIColor color = (UIColor)colorRef;

[self nf_setBackgroundColor:(id)color.grayDraw.CGColor];

} else {

CGColorRef color = (__bridge CGColorRef)colorRef;

[self nf_setBackgroundColor:(id)[UIColor colorWithCGColor:color].grayDraw.CGColor];

}

} else {

[self nf_setBackgroundColor:colorRef];

}

}





(void)nf_setShadowColor:(id)colorRef {

if (self.themeTag != NFThemeNoDrawTag) {

if ([colorRef isKindOfClass:UIColor.class]) {

UIColor color = (UIColor)colorRef;

[self nf_setShadowColor:(id)color.grayDraw.CGColor];

} else {

CGColorRef color = (__bridge CGColorRef)colorRef;

[self nf_setShadowColor:(id)[UIColor colorWithCGColor:color].grayDraw.CGColor];

}

} else {

[self nf_setShadowColor:colorRef];

}

}





(void)nf_setBorderColor:(id)colorRef {

if (self.themeTag != NFThemeNoDrawTag) {

if ([colorRef isKindOfClass:UIColor.class]) {

UIColor color = (UIColor)colorRef;

[self nf_setBorderColor:(id)color.grayDraw.CGColor];

} else {

CGColorRef color = (__bridge CGColorRef)colorRef;

[self nf_setBorderColor:(id)[UIColor colorWithCGColor:color].grayDraw.CGColor];

}

} else {

[self nf_setBorderColor:colorRef];

}

}







—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
